"""Cross-site product matching.

The problem: the *same* physical product appears as

    1688     "2024新款TWS蓝牙耳机5.3无线降噪运动耳机厂家批发"        ¥18.50  MOQ 2
    AliExpress "TWS Wireless Bluetooth 5.3 Earbuds Noise Cancelling Sport Headset"  $7.99
    DHgate    "Wholesale TWS Earbuds BT5.3 ANC Sports Headphones Lot"      $5.40  MOQ 5

No shared identifier, three languages of keyword soup, three price bases. Deciding
these are one product is the entire value of this system, and getting it wrong in
either direction is bad: over-merging fuses unrelated products into a nonsense page,
under-merging leaves you comparing nothing.

Approach -- cheap deterministic signals first, fuzzy ones only as tie-breakers:

  1. **GTIN** (UPC/EAN, checksum-validated). Exact match => merge, score 1.0, done.
  2. **Brand + MPN.** Near-certain; only real risk is a reused part number.
  3. **Perceptual image hash.** These marketplaces reuse the identical supplier
     photo across every reseller, so this is unreasonably effective. Candidates are
     generated by LSH banding (4 x 16-bit bands) then scored by Hamming distance.
  4. **Normalized title similarity** (token-set ratio after stripping marketing
     filler), on the *English* title so Chinese and English listings are comparable.
  5. **Spec agreement.** Overlapping normalized spec keys that share a value.

Signals 3-5 are combined into a weighted score. Above ``auto_merge_threshold`` the
offer joins the product; between ``review_threshold`` and that it goes to a human
review queue rather than guessing. Weights live in ``config.yaml``.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Optional, Sequence

from rapidfuzz import fuzz
from sqlalchemy import func, or_, select
from sqlalchemy.orm import Session

from ..config import CrawlConfig, load_crawl_config
from ..db.models import (
    CanonicalProduct,
    Image,
    MatchRejection,
    MatchReview,
    Offer,
    OfferSpec,
)
from ..util.text import (
    codes_conflict,
    extract_model_codes,
    normalize_spec_key,
    normalize_title,
    title_tokens,
)
from .images import phash_similarity

log = logging.getLogger(__name__)

DEFAULT_WEIGHTS = {
    "gtin": 1.00,
    "mpn": 0.92,
    "image_phash": 0.45,
    "title": 0.35,
    "specs": 0.20,
}


@dataclass
class MatchResult:
    product: Optional[CanonicalProduct]
    score: float
    method: str
    signals: dict = field(default_factory=dict)

    @property
    def matched(self) -> bool:
        return self.product is not None


class MatchEngine:
    def __init__(self, session: Session, config: CrawlConfig | None = None):
        self.session = session
        cfg = (config or load_crawl_config()).matching
        self.auto_threshold = float(cfg.get("auto_merge_threshold", 0.86))
        self.review_threshold = float(cfg.get("review_threshold", 0.70))
        self.max_phash_distance = int(cfg.get("image_phash_max_distance", 10))
        self.weights = {**DEFAULT_WEIGHTS, **(cfg.get("weights") or {})}

    # --------------------------------------------------------------- public API

    def match(self, offer: Offer, specs: Sequence[OfferSpec] = ()) -> MatchResult:
        """Find the best existing canonical product for ``offer``."""
        # A human ruling outranks every automated signal below, including an exact
        # identifier match -- they looked at both listings and said no.
        blocked = self.blocked_canonical_ids(offer)
        # An offer can never "match" the product it already sits on: the question is
        # always which *other* product it should join. Without this, an offer on a
        # single-offer product scores 1.0 against itself and rematch/manual callers
        # get a meaningless self-merge proposal.
        if offer.canonical_id is not None:
            blocked = blocked | {offer.canonical_id}

        # --- tier 1: hard identifiers ------------------------------------
        if offer.gtin:
            hit = self.session.scalar(
                select(CanonicalProduct).where(CanonicalProduct.gtin == offer.gtin)
            )
            if hit and hit.id in blocked:
                # Contradictory: identical validated GTINs that a human split apart.
                # Usually means one side's GTIN is wrong. Worth investigating, so
                # say so loudly rather than silently discarding either signal.
                log.warning(
                    "offer %s and product %s share GTIN %s but were rejected by a "
                    "human; honouring the rejection. Check the GTIN on both.",
                    offer.id, hit.id, offer.gtin,
                )
            elif hit:
                return MatchResult(hit, 1.0, "gtin", {"gtin": offer.gtin})

        if offer.mpn and offer.brand:
            hit = self.session.scalar(
                select(CanonicalProduct).where(
                    func.lower(CanonicalProduct.mpn) == offer.mpn.lower(),
                    func.lower(CanonicalProduct.brand) == offer.brand.lower(),
                )
            )
            if hit and hit.id not in blocked:
                return MatchResult(
                    hit, self.weights["mpn"], "brand_mpn",
                    {"mpn": offer.mpn, "brand": offer.brand},
                )

        # --- tier 2: fuzzy scoring over a candidate set -------------------
        candidates = [c for c in self._candidates(offer) if c.id not in blocked]
        if not candidates:
            return MatchResult(None, 0.0, "none")

        offer_phashes = self._offer_phashes(offer)
        offer_specs = _spec_map(specs)
        offer_title = offer.title_en or offer.title_raw
        offer_tokens = title_tokens(offer_title)
        offer_codes = set(extract_model_codes(offer_title))

        best: Optional[MatchResult] = None
        for product in candidates:
            score, signals = self._score(
                product, offer, offer_title, offer_tokens, offer_codes,
                offer_phashes, offer_specs,
            )
            if best is None or score > best.score:
                best = MatchResult(product, score, "weighted", signals)

        assert best is not None
        if best.score >= self.auto_threshold:
            return best
        if best.score >= self.review_threshold:
            best.method = "review"
            return best
        return MatchResult(None, best.score, "below_threshold", best.signals)

    def apply(self, offer: Offer, result: MatchResult) -> CanonicalProduct:
        """Attach the offer to a product, creating or queueing review as needed."""
        if result.method == "review" and result.product is not None:
            self.session.add(
                MatchReview(
                    offer_id=offer.id,
                    canonical_id=result.product.id,
                    score=result.score,
                    signals=result.signals,
                    status="pending",
                )
            )
            # Don't guess: give the offer its own product until a human rules.
            return self.create_product(offer)

        if result.matched and result.product is not None:
            offer.canonical_id = result.product.id
            offer.match_score = result.score
            offer.match_method = result.method
            return result.product

        return self.create_product(offer)

    def create_product(self, offer: Offer) -> CanonicalProduct:
        from slugify import slugify

        title = offer.title_en or offer.title_raw
        base = slugify(title)[:170] or f"product-{offer.id}"
        slug = base
        n = 2
        while self.session.scalar(select(CanonicalProduct.id).where(CanonicalProduct.slug == slug)):
            slug = f"{base}-{n}"
            n += 1

        product = CanonicalProduct(
            slug=slug,
            title_en=title[:512],
            brand=offer.brand,
            model=offer.model,
            mpn=offer.mpn,
            gtin=offer.gtin,
            description_en=offer.description_en or offer.description_raw,
            specs={},
        )
        self.session.add(product)
        self.session.flush()

        offer.canonical_id = product.id
        offer.match_score = 1.0
        offer.match_method = "new"
        return product

    # -------------------------------------------------------- human rejections

    def blocked_canonical_ids(self, offer: Offer) -> set[int]:
        """Products this offer must never join, per previous human rulings.

        Resolved at query time: rejections are stored offer-to-offer, so whichever
        product the rejected counterpart currently belongs to is what gets blocked.
        A product that later absorbs a rejected listing becomes blocked too, which
        is the desired behaviour -- the offer was judged different from that thing.
        """
        if offer.id is None:
            return set()

        rows = self.session.execute(
            select(MatchRejection.low_offer_id, MatchRejection.high_offer_id).where(
                or_(
                    MatchRejection.low_offer_id == offer.id,
                    MatchRejection.high_offer_id == offer.id,
                )
            )
        ).all()
        if not rows:
            return set()

        partners = {(high if low == offer.id else low) for low, high in rows}
        return {
            int(cid)
            for (cid,) in self.session.execute(
                select(Offer.canonical_id).where(
                    Offer.id.in_(partners), Offer.canonical_id.is_not(None)
                )
            ).all()
        }

    # ------------------------------------------------------- candidate blocking

    def _candidates(self, offer: Offer, limit: int = 60) -> list[CanonicalProduct]:
        """Narrow millions of products to a few dozen worth scoring."""
        ids: set[int] = set()

        # (a) products sharing a near-identical image
        for band_col, band_val in _phash_band_filters(self._offer_phashes(offer)):
            rows = self.session.execute(
                select(Image.canonical_id, Image.offer_id)
                .where(band_col == band_val, Image.phash.is_not(None))
                .limit(400)
            ).all()
            for canonical_id, offer_id in rows:
                if canonical_id:
                    ids.add(int(canonical_id))
                elif offer_id:
                    cid = self.session.scalar(
                        select(Offer.canonical_id).where(Offer.id == offer_id)
                    )
                    if cid:
                        ids.add(int(cid))
            if len(ids) > limit * 3:
                break

        # (b) products whose title shares distinctive tokens
        ids |= set(self._title_candidates(offer, limit))

        # (c) same model code
        for code in extract_model_codes(offer.title_en or offer.title_raw)[:3]:
            rows = self.session.scalars(
                select(CanonicalProduct.id)
                .where(
                    or_(
                        CanonicalProduct.model.ilike(f"%{code}%"),
                        CanonicalProduct.mpn.ilike(f"%{code}%"),
                    )
                )
                .limit(20)
            ).all()
            ids.update(int(r) for r in rows)

        if not ids:
            return []
        # Products emptied by a split or a prune are still reachable through their
        # old images and FTS rows. Merging into one would move the offer onto a dead
        # page, so they are never candidates.
        return list(
            self.session.scalars(
                select(CanonicalProduct)
                .where(
                    CanonicalProduct.id.in_(list(ids)[: limit * 4]),
                    CanonicalProduct.is_active.is_(True),
                )
                .limit(limit * 4)
            ).all()
        )

    def _title_candidates(self, offer: Offer, limit: int) -> list[int]:
        from ..db.search import search_product_ids

        title = normalize_title(offer.title_en or offer.title_raw)
        if not title:
            return []
        # Rare tokens discriminate; common ones ("wireless") do not. Longest-first
        # is a cheap proxy for rarity that needs no IDF table.
        tokens = sorted(set(title.split()), key=len, reverse=True)[:6]
        if not tokens:
            return []
        try:
            hits = search_product_ids(self.session, " ".join(tokens), limit=limit)
        except Exception as e:
            log.debug("fts candidate lookup failed: %s", e)
            return []
        return [pid for pid, _ in hits]

    # ------------------------------------------------------------------ scoring

    def _score(
        self,
        product: CanonicalProduct,
        offer: Offer,
        offer_title: str,
        offer_tokens: set[str],
        offer_codes: set[str],
        offer_phashes: list[str],
        offer_specs: dict[str, str],
    ) -> tuple[float, dict]:
        signals: dict = {}

        # Hard disqualifier: two *different* known GTINs can never be one product.
        if offer.gtin and product.gtin and offer.gtin != product.gtin:
            return 0.0, {"reject": "gtin_conflict"}
        # Same for conflicting model codes when both sides state one.
        product_codes = set(extract_model_codes(product.title_en)) | set(
            extract_model_codes(product.model)
        )
        if codes_conflict(offer_codes, product_codes):
            signals["code_conflict"] = True

        # --- image ---
        img_score = 0.0
        for a in offer_phashes:
            for b in self._product_phashes(product):
                img_score = max(img_score, phash_similarity(a, b, self.max_phash_distance))
                if img_score >= 0.99:
                    break
        signals["image"] = round(img_score, 3)

        # --- title ---
        product_tokens = title_tokens(product.title_en)
        title_score = 0.0
        if offer_tokens and product_tokens:
            token_ratio = fuzz.token_set_ratio(
                normalize_title(offer_title), normalize_title(product.title_en)
            ) / 100.0
            jaccard = len(offer_tokens & product_tokens) / len(offer_tokens | product_tokens)
            title_score = 0.6 * token_ratio + 0.4 * jaccard
        signals["title"] = round(title_score, 3)

        # --- specs ---
        spec_score, overlap = _spec_agreement(offer_specs, product.specs or {})
        signals["specs"] = round(spec_score, 3)
        signals["spec_overlap"] = overlap

        # --- model code bonus ---
        code_bonus = 0.12 if (offer_codes & product_codes) else 0.0
        signals["code_match"] = bool(offer_codes & product_codes)

        # --- combine -------------------------------------------------------
        # Only signals that could actually be *evaluated* contribute. A listing
        # with no spec table shouldn't be penalised as though its specs disagreed;
        # renormalizing over available evidence is the difference between "we have
        # no information" and "we have contrary information".
        w = self.weights
        parts: list[tuple[float, float]] = []
        if offer_phashes and self._product_phashes(product):
            parts.append((img_score, w["image_phash"]))
        if offer_tokens and product_tokens:
            parts.append((title_score, w["title"]))
        if overlap:
            parts.append((spec_score, w["specs"]))

        if not parts:
            return 0.0, {**signals, "reject": "no_comparable_signals"}

        base = sum(s * weight for s, weight in parts) / sum(weight for _, weight in parts)

        # Domain rule: these marketplaces reuse the *same supplier photograph* across
        # resellers, so a near-identical image is a strong prior. It is not conclusive
        # on its own -- colour/capacity variants share photography too -- so the title
        # acts as the discriminator on top of it.
        strong_image = img_score >= 0.85
        if strong_image and title_score >= 0.40:
            score = max(base, 0.90)
        elif strong_image and spec_score >= 0.8 and overlap >= 2:
            score = max(base, 0.88)
        elif strong_image and title_score < 0.25:
            # Same photo, unrelated titles: almost always a variant or a reused stock
            # photo. Send it to a human rather than guessing either way.
            score = min(base, self.review_threshold + 0.05)
        else:
            score = base

        score = min(1.0, score + code_bonus)
        if signals.get("code_conflict"):
            score *= 0.75

        signals["base"] = round(base, 3)
        return round(score, 4), signals

    # ------------------------------------------------------------------ helpers

    def _offer_phashes(self, offer: Offer) -> list[str]:
        if offer.id is None:
            return []
        rows = self.session.scalars(
            select(Image.phash)
            .where(Image.offer_id == offer.id, Image.phash.is_not(None))
            .order_by(Image.position)
            .limit(4)
        ).all()
        return [r for r in rows if r]

    def _product_phashes(self, product: CanonicalProduct) -> list[str]:
        rows = self.session.execute(
            select(Image.phash)
            .join(Offer, Offer.id == Image.offer_id, isouter=True)
            .where(
                or_(Image.canonical_id == product.id, Offer.canonical_id == product.id),
                Image.phash.is_not(None),
            )
            .limit(12)
        ).all()
        return [r[0] for r in rows if r[0]]


# ---------------------------------------------------------------- band indexing


def _phash_band_filters(phashes: list[str]):
    """LSH banding: split each 64-bit hash into 4 x 16-bit bands.

    Two hashes differing by <=3 bits must agree exactly on at least one band
    (pigeonhole), which is precisely the "same photo, re-encoded" case that
    dominates these marketplaces. Larger distances are still caught via the title
    and spec candidate paths.
    """
    from sqlalchemy import func as sa_func

    filters = []
    for ph in phashes[:2]:
        if not ph or len(ph) < 16:
            continue
        for i in range(4):
            band = ph[i * 4 : (i + 1) * 4]
            filters.append((sa_func.substr(Image.phash, i * 4 + 1, 4), band))
    return filters


def _spec_map(specs: Sequence[OfferSpec]) -> dict[str, str]:
    out: dict[str, str] = {}
    for s in specs:
        key = s.key_norm or normalize_spec_key(s.key_en or s.key_raw)
        val = (s.value_en or s.value_raw or "").strip().lower()
        if key and val:
            out.setdefault(key, val)
    return out


_NUM_RE = re.compile(r"\d+(?:\.\d+)?")


def _spec_agreement(a: dict[str, str], b: dict[str, str]) -> tuple[float, int]:
    """Fraction of shared spec keys whose values agree. Returns (score, overlap).

    Both sides are lower-cased first: offer specs are keyed by ``normalize_spec_key``
    output (lower case) while a product's merged sheet is keyed for display (title
    case), so a case-sensitive intersection is always empty.
    """
    a = {str(k).strip().lower(): str(v).strip().lower() for k, v in a.items()}
    b = {str(k).strip().lower(): str(v).strip().lower() for k, v in b.items()}
    shared = set(a) & set(b)
    # Free-text keys are noisy and near-universal; they add nothing discriminative.
    shared -= {"description", "name", "keywords", "packing", "origin"}
    if not shared:
        return 0.0, 0

    agree = 0.0
    for key in shared:
        va, vb = a[key], b[key]
        if va == vb:
            agree += 1.0
            continue
        # Numeric values: compare the numbers, ignore unit formatting differences.
        na, nb = _NUM_RE.findall(va), _NUM_RE.findall(vb)
        if na and nb and na[0] == nb[0]:
            agree += 0.9
            continue
        ratio = fuzz.token_set_ratio(va, vb) / 100.0
        if ratio > 0.85:
            agree += ratio
    return agree / len(shared), len(shared)


# --------------------------------------------------------- rejection recording


def record_rejection(
    session: Session, offer_id: int, canonical_id: int, *, note: str | None = None
) -> int:
    """Record "this offer is not that product" and make it stick.

    Expands to one pair per offer currently in the product, because that is what
    the human actually judged -- they compared the incoming listing against the
    listings on that page. Blocking only the product id would evaporate the moment
    the product was rebuilt or re-slugged.

    Returns the number of new pairs recorded.
    """
    members = [
        int(oid)
        for (oid,) in session.execute(
            select(Offer.id).where(
                Offer.canonical_id == canonical_id, Offer.id != offer_id
            )
        ).all()
    ]
    if not members:
        return 0

    existing = {
        (low, high)
        for low, high in session.execute(
            select(MatchRejection.low_offer_id, MatchRejection.high_offer_id).where(
                or_(
                    MatchRejection.low_offer_id == offer_id,
                    MatchRejection.high_offer_id == offer_id,
                )
            )
        ).all()
    }

    added = 0
    for other in members:
        pair = MatchRejection.normalize(offer_id, other)
        if pair in existing:
            continue
        session.add(
            MatchRejection(low_offer_id=pair[0], high_offer_id=pair[1], note=note)
        )
        existing.add(pair)
        added += 1
    return added


def clear_rejections(session: Session, offer_id: int, canonical_id: int) -> int:
    """Undo the rejections between an offer and a product. Returns rows removed.

    Without this a mistaken click would be permanent and unfixable from the UI,
    which is a bad property for a decision the system then treats as authoritative.
    """
    members = [
        int(oid)
        for (oid,) in session.execute(
            select(Offer.id).where(Offer.canonical_id == canonical_id)
        ).all()
    ]
    if not members:
        return 0

    removed = 0
    for other in members:
        if other == offer_id:
            continue
        low, high = MatchRejection.normalize(offer_id, other)
        row = session.scalar(
            select(MatchRejection).where(
                MatchRejection.low_offer_id == low,
                MatchRejection.high_offer_id == high,
            )
        )
        if row is not None:
            session.delete(row)
            removed += 1
    return removed


def detach_offer(session: Session, offer: Offer) -> Optional[CanonicalProduct]:
    """Move an offer onto a product of its own, rebuilding the one it left.

    Needed when a human rejects a merge that already happened: recording the
    rejection alone would leave the bad merge standing.
    """
    from ..db.search import index_product

    old_id = offer.canonical_id
    engine_product = None
    if old_id is not None:
        offer.canonical_id = None
        session.flush()

    engine_product = MatchEngine(session).create_product(offer)
    session.flush()

    if old_id is not None and old_id != engine_product.id:
        old = session.get(CanonicalProduct, old_id)
        if old is not None:
            rebuild_product(session, old)
            index_product(session, old)
    rebuild_product(session, engine_product)
    index_product(session, engine_product)
    return engine_product


# ------------------------------------------------------------ product rollups


def rebuild_product(session: Session, product: CanonicalProduct) -> None:
    """Recompute the merged spec sheet, price rollups and primary image.

    Called after any offer attaches to or detaches from the product. This is what
    keeps the item page correct without recomputing anything at request time.
    """
    offers = list(
        session.scalars(
            select(Offer).where(Offer.canonical_id == product.id, Offer.is_active.is_(True))
        ).all()
    )
    product.offer_count = len(offers)
    product.site_count = len({o.site_id for o in offers})

    if not offers:
        product.is_active = False
        product.best_price_usd = product.best_landed_usd = product.max_price_usd = None
        return

    product.is_active = True

    priced = [o for o in offers if o.price_usd is not None and o.price_usd > 0]
    if priced:
        cheapest = min(priced, key=lambda o: o.price_usd or 0.0)
        product.best_price_usd = cheapest.price_usd
        product.best_price_site_id = cheapest.site_id
        product.max_price_usd = max(o.price_usd or 0.0 for o in priced)

    landed = [o.landed_cost_usd for o in offers if o.landed_cost_usd is not None]
    product.best_landed_usd = min(landed) if landed else None
    product.min_moq = min((o.moq or 1) for o in offers)
    product.last_seen = max(o.last_seen for o in offers)

    # --- merged spec sheet -------------------------------------------------
    # Prefer values agreed on by the most offers; ties break toward the offer with
    # the richest spec table, which is usually the manufacturer listing.
    votes: dict[str, dict[str, int]] = {}
    for offer in offers:
        specs = session.scalars(
            select(OfferSpec).where(OfferSpec.offer_id == offer.id)
        ).all()
        for s in specs:
            key = s.key_norm or normalize_spec_key(s.key_en or s.key_raw)
            val = (s.value_en or s.value_raw or "").strip()
            if not key or not val or len(key) > 80:
                continue
            votes.setdefault(key.title(), {}).setdefault(val, 0)
            votes[key.title()][val] += 1

    product.specs = {
        key: max(vals.items(), key=lambda kv: (kv[1], len(kv[0])))[0]
        for key, vals in sorted(votes.items())
        if vals
    }

    # --- identity fields: first non-null wins, preferring verified suppliers ----
    for offer in sorted(offers, key=lambda o: (not o.is_verified_supplier, o.id)):
        product.brand = product.brand or offer.brand
        product.model = product.model or offer.model
        product.mpn = product.mpn or offer.mpn
        product.gtin = product.gtin or offer.gtin
        if not product.description_en:
            product.description_en = offer.description_en or offer.description_raw

    # --- primary image: largest image from the offer with the best photo ---
    img = session.scalar(
        select(Image)
        .join(Offer, Offer.id == Image.offer_id)
        .where(Offer.canonical_id == product.id, Image.local_path.is_not(None))
        .order_by((Image.width * Image.height).desc())
        .limit(1)
    )
    if img is not None:
        product.primary_image_id = img.id

    # An English title is what users search; prefer a genuinely English one.
    english_titles = [
        o.title_en for o in offers
        if o.title_en and o.source_lang in ("en", "und", None)
    ]
    if english_titles:
        # Median length avoids both truncated stubs and 200-char keyword dumps.
        english_titles.sort(key=len)
        product.title_en = english_titles[len(english_titles) // 2][:512]
