"""Demo data so you can see the UI before running a real crawl.

``python -m sourcehub.cli demo-seed`` ingests a handful of representative listings
through the *real* pipeline -- same matching, same rollups, same category
resolution -- so the item page shows exactly what a live crawl produces, including
a three-site comparison and a Chinese listing that needs a forwarding agent.

Images are generated locally rather than downloaded, so this works offline.
"""

from __future__ import annotations

import io
import logging

from .db.session import init_db, session_scope
from .pipeline.ingest import IngestContext, ingest_offer
from .scrapers.base import RawOffer, RawSpec, RawTier

log = logging.getLogger(__name__)


def _swatch(color: tuple[int, int, int], seed: int, size: int = 500) -> bytes:
    """Distinct placeholder art per product.

    Deliberately different *shapes*, not just different colours: perceptual hashing
    keys on structure, so recolouring one motif would leave every demo product a
    near-match of every other and make reverse image search look broken.
    """
    from PIL import Image as PILImage, ImageDraw

    img = PILImage.new("RGB", (size, size), (245, 246, 248))
    d = ImageDraw.Draw(img)
    m = 60

    if seed == 0:        # earbuds - two discs, lower half
        d.ellipse([m, size // 2 - 40, size // 2 - 20, size - m], fill=color)
        d.ellipse([size // 2 + 20, size // 2 - 40, size - m, size - m], fill=color)
        d.rectangle([m + 30, m, m + 70, size // 2], fill=(30, 30, 36))
    elif seed == 2:      # hub - wide bar with ports along the top
        d.rounded_rectangle([m, size // 2 - 70, size - m, size // 2 + 70],
                            radius=26, fill=color)
        for i in range(5):
            x = m + 30 + i * 70
            d.rectangle([x, size // 2 - 46, x + 40, size // 2 - 6], fill=(240, 240, 245))
    else:                # drill - circle plus a vertical grip
        d.ellipse([m, m, size - m, size - m], fill=color)
        d.rectangle([size // 2 - 34, size // 2, size // 2 + 34, size - 20],
                    fill=(35, 35, 40))
        d.ellipse([size // 2 - 60, size // 2 - 60, size // 2 + 60, size // 2 + 60],
                  fill=(250, 250, 250))

    buf = io.BytesIO()
    img.save(buf, "PNG")
    return buf.getvalue()


IMAGES = {
    "earbuds": _swatch((36, 92, 196), 0),
    "hub": _swatch((28, 150, 120), 2),
    "drill": _swatch((208, 118, 26), 4),
}


class _LocalImageFetcher:
    """Serves the generated bytes instead of hitting the network."""

    def download(self, url: str, referer: str | None = None) -> bytes:
        for key, data in IMAGES.items():
            if key in url:
                return data
        raise RuntimeError(f"no demo image for {url}")

    def close(self) -> None:
        pass


LISTINGS = [
    # --- one product, three marketplaces, two languages ---------------------
    RawOffer(
        site_key="aliexpress", site_product_id="demo-1005006123456",
        url="https://www.aliexpress.com/item/1005006123456.html",
        title="TWS Wireless Bluetooth 5.3 Earbuds Active Noise Cancelling Sport Headset",
        currency="USD", price_min=7.99, moq=1,
        shipping_cost=2.50, shipping_currency="USD", shipping_from="China",
        shipping_note="Delivery in 12-20 days via AliExpress Standard Shipping",
        seller_name="TopSound Official Store", rating=4.7, orders_count=3120,
        image_urls=["https://demo.local/earbuds.png"],
        category_path="Consumer Electronics > Earphones & Headphones",
        specs=[RawSpec("Bluetooth Version", "5.3", 0), RawSpec("Battery Capacity", "40mAh", 1),
               RawSpec("Brand Name", "Lenovo", 2), RawSpec("Waterproof Grade", "IPX5", 3),
               RawSpec("Charging Case Capacity", "300mAh", 4)],
        detail_fetched=True,
    ),
    RawOffer(
        site_key="1688", site_product_id="demo-678901234",
        url="https://detail.1688.com/offer/678901234.html",
        title="2024新款TWS蓝牙耳机5.3无线降噪运动耳机厂家批发",
        currency="CNY", price_min=18.50, moq=2, moq_unit="piece",
        seller_name="深圳市声美电子有限公司", shipping_from="广东 深圳",
        image_urls=["https://demo.local/earbuds.png"],
        tiers=[RawTier(2, 99, 18.50, "CNY"), RawTier(100, 999, 15.80, "CNY"),
               RawTier(1000, None, 13.20, "CNY")],
        specs=[RawSpec("蓝牙版本", "5.3", 0), RawSpec("电池容量", "40mAh", 1),
               RawSpec("防水等级", "IPX5", 2)],
        fees_note="Domestic-China listing. International shipping and any service fee "
                  "are charged by your forwarding agent, not by 1688.",
        detail_fetched=True,
    ),
    RawOffer(
        site_key="dhgate", site_product_id="demo-998877665",
        url="https://www.dhgate.com/product/tws-earbuds/998877665.html",
        title="Wholesale TWS Earbuds BT 5.3 ANC Sports Bluetooth Headphones Lot",
        currency="USD", price_min=5.40, moq=5,
        shipping_cost=6.00, shipping_currency="USD",
        seller_name="ShenzhenAudioDirect", rating=4.4, review_count=812,
        image_urls=["https://demo.local/earbuds.png"],
        specs=[RawSpec("Bluetooth Version", "5.3", 0), RawSpec("Brand Name", "Lenovo", 1)],
        detail_fetched=True,
    ),

    # --- a second multi-site product ----------------------------------------
    RawOffer(
        site_key="banggood", site_product_id="demo-1554999",
        url="https://www.banggood.com/usb-c-hub-p-1554999.html",
        title="8-in-1 USB C Hub Docking Station 4K HDMI PD100W SD Card Reader",
        currency="USD", price_min=24.99, moq=1, shipping_free=True,
        seller_name="Banggood", rating=4.6, review_count=1204,
        image_urls=["https://demo.local/hub.png"],
        category_path="Electronics > Computer Peripherals",
        specs=[RawSpec("Ports", "8", 0), RawSpec("HDMI Output", "4K@30Hz", 1),
               RawSpec("Power Delivery", "100W", 2), RawSpec("Brand Name", "Rocketek", 3)],
        detail_fetched=True,
    ),
    RawOffer(
        site_key="alibaba", site_product_id="demo-60812345678",
        url="https://www.alibaba.com/product-detail/usb-c-hub_60812345678.html",
        title="Wholesale 8 in 1 Type C Hub Docking Station 4K HDMI PD 100W SD Card Reader",
        currency="USD", price_min=9.80, moq=100, moq_unit="piece",
        seller_name="Shenzhen Rocketek Electronics Co., Ltd.",
        is_verified_supplier=True, seller_years=9, lead_time_days=15,
        image_urls=["https://demo.local/hub.png"],
        category_path="Consumer Electronics > Computer Accessories",
        tiers=[RawTier(100, 499, 9.80, "USD"), RawTier(500, 1999, 8.60, "USD"),
               RawTier(2000, None, 7.40, "USD")],
        specs=[RawSpec("Ports", "8", 0), RawSpec("HDMI Output", "4K@30Hz", 1),
               RawSpec("Power Delivery", "100W", 2), RawSpec("Brand Name", "Rocketek", 3),
               RawSpec("Place of Origin", "Guangdong, China", 4)],
        fees_note="FOB Shenzhen. Freight, duty and customs clearance are additional.",
        detail_fetched=True,
    ),

    # --- a single-site product ----------------------------------------------
    RawOffer(
        site_key="banggood", site_product_id="demo-1554321",
        url="https://www.banggood.com/cordless-drill-p-1554321.html",
        title="21V Cordless Impact Drill Brushless Electric Screwdriver Power Tool Kit",
        currency="USD", price_min=42.99, moq=1, shipping_free=True,
        seller_name="Banggood", rating=4.5, review_count=331,
        image_urls=["https://demo.local/drill.png"],
        specs=[RawSpec("Voltage", "21V", 0), RawSpec("Brand Name", "Hilda", 1),
               RawSpec("Max Torque", "45N.m", 2)],
        detail_fetched=True,
    ),
]


def seed_demo() -> int:
    """Ingest the demo listings. Returns the number processed."""
    init_db()
    with session_scope() as session:
        ctx = IngestContext(session)
        ctx.images._fetcher = _LocalImageFetcher()
        try:
            for raw in LISTINGS:
                offer = ingest_offer(ctx, raw)
                log.info(
                    "  %-12s -> $%s (MOQ %s) product #%s",
                    raw.site_key, offer.price_usd, offer.moq, offer.canonical_id,
                )
        finally:
            ctx.close()
    return len(LISTINGS)
